VIA_ENABLE = yes
VIAL_ENABLE = yes

LTO_ENABLE = yes

CONSOLE_ENABLE = no
COMMAND_ENABLE = no
AUDIO_ENABLE = no
SPACE_CADET_ENABLE = no
GRAVE_ESC_ENABLE = no
MAGIC_ENABLE = no

QMK_SETTINGS = no
KEY_OVERRIDE_ENABLE = no
REPEAT_KEY_ENABLE = no

COMBO_ENABLE = yes
TAP_DANCE_ENABLE = yes
