VIA_ENABLE = yes
VIAL_ENABLE = yes

# Reduce ROM usage for ATmega32U2.
NO_ACTION_ONESHOT = yes
NO_ACTION_TAPPING = yes
NO_ACTION_LAYER = yes
NO_ACTION_MACRO = yes
NO_ACTION_FUNCTION = yes
NO_MUSIC = yes
NO_MUSIC_MAP = yes
NO_VELOCIKEY = yes
NO_COMBINED_KEYS = yes
NO_ALT_TAB = yes
NO_REPEAT_KEY = yes
NO_KEY_OVERRIDE = yes
NO_CAPS_WORD = yes
NO_AUTO_SHIFT = yes
NO_GRAVE_ESC = yes
NO_MAGIC = yes
NO_SWAP_HANDS = yes
NO_OSM = yes
NO_TAP_DANCE = yes
NO_TRI_LAYER = yes
NO_LOCKING_SUPPORT = yes
